# Generated by Django 5.1.2 on 2024-12-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '本のデータ'},
        ),
        migrations.AddField(
            model_name='book',
            name='thumnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
