# Generated by Django 5.1.2 on 2024-12-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_options_alter_book_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
