# Generated by Django 5.1.2 on 2024-12-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('comics', '漫画'), ('life', '生活'), ('other', 'その他')], max_length=100),
        ),
    ]
